# Generated by Django 3.2.6 on 2021-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Phoneno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('1', 'MALE'), ('2', 'OTHER'), ('3', 'FEMALE')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('india', '+91'), ('australia', '+02')], max_length=100)),
            ],
        ),
    ]
