# Generated by Django 3.2.3 on 2021-11-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_message_stories_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='mes',
            field=models.CharField(max_length=200),
        ),
    ]
